### ISSUE TITLE
Unreachable Error 

### ISSUE THREAD

**Issue by redouard2** [Retrockit/ansible_lab#1]
Entered control node and cd into ansible and tried to reach to all nodes via 'ansible multi -a "echo blah blah" ' Got an unreachable error on all three nodes stating failed to connect.

![Unreachable](https://user-images.githubusercontent.com/73624384/139562251-b27360c7-148c-4943-906a-738ac6d2924a.png)

**Comment by Retrockit** [comment]
I've created a separate branch with a potential fix for the above error.

First, delete the ansible_lab repo on your machine

Copy + Paste this line your powershell: 

`
git clone -b Issue_Unreachable_Error_Fix https://github.com/Retrockit/ansible_lab.git`

This will clone that specific branch to your current directory.

Test and let me know if you run into anymore problems.

**Comment by redouard2** [comment]
Problem is fixed, thank you for the fix!
